grafana:
  admin:
    existingSecret: monitoring-grafana
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.woulf.fr
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - hosts:
          - grafana.woulf.fr
        secretName: grafana-woulf-tls
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Viewer
      hide_version: true

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
