apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: woulf-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: woulf.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio
            port:
              number: 3000
